### ISSUE TITLE
[Heroku] Stuck on swapping planets

### ISSUE THREAD

**Issue by SakhG** [South-Paw/salien-script-js#43]
This message was spamming logs

`>> Leaving planet 27, because we want to be on 33`

I restarted node heroku.js and everything became normal, not sure what happened 

My guess is something happened when new planet appeared (33) when we were on a planet that was already gone (27) somehow

**Comment by South-Paw** [comment]
Hi there, I fixed this under #32 last night at about 2:30am my time but have yet to test it properly or push out an update - will leave this open until I'm sure it works and has been pushed out.

**Comment by SakhJack** [comment]
Problem persists. some new logs, maybe will help
`2018-06-29T06:34:12.246050+00:00 app[salien.1]: [06:34:12] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:12.379219+00:00 app[salien.1]: [06:34:12] (sakhjack) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:12.502378+00:00 app[salien.1]: [06:34:12] (sakhjack) SalienScriptRestart: !! Wrong current Planet 30

2018-06-29T06:34:12.502475+00:00 app[salien.1]: [06:34:12] (sakhjack)  Script will restart in 5 seconds... 

2018-06-29T06:34:12.502478+00:00 app[salien.1]: 

2018-06-29T06:34:12.502479+00:00 app[salien.1]: 

2018-06-29T06:34:12.992663+00:00 app[salien.1]: [06:34:12] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:13.783863+00:00 app[salien.1]: [06:34:13] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:14.711291+00:00 app[salien.1]: [06:34:14] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:15.498345+00:00 app[salien.1]: [06:34:15] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:16.270110+00:00 app[salien.1]: [06:34:16] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:17.242459+00:00 app[salien.1]: [06:34:17] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:17.503257+00:00 app[salien.1]: 

2018-06-29T06:34:17.503387+00:00 app[salien.1]: [06:34:17] (sakhjack)  Started SalienScript | Version: 0.0.13 

2018-06-29T06:34:17.503472+00:00 app[salien.1]: [06:34:17] (sakhjack)  Thanks for choosing https://github.com/South-Paw/salien-script-js 

2018-06-29T06:34:17.503568+00:00 app[salien.1]: [06:34:17] (sakhjack)  Remeber to drop us a ⭐ star on the project if you appreciate this script! 

2018-06-29T06:34:17.503574+00:00 app[salien.1]: 

2018-06-29T06:34:17.640230+00:00 app[salien.1]: [06:34:17] (sakhjack) Scanning all planets for next best zone...

2018-06-29T06:34:17.663802+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Planet  29 (Captured: 89.77%) - Hard:  0 - Medium:  0 - Easy: 20 - Players: 191,995 (Mold-breaking Metroidvanias II)

2018-06-29T06:34:17.663977+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Planet  31 (Captured: 88.42%) - Hard:  0 - Medium:  0 - Easy: 15 - Players: 194,109 (Spikes)

2018-06-29T06:34:17.664185+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Planet  32 (Captured: 74.03%) - Hard:  0 - Medium:  0 - Easy: 31 - Players: 158,531 (Alternate History)

2018-06-29T06:34:17.664397+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Planet  33 (Captured: 70.23%) - Hard:  0 - Medium:  0 - Easy: 31 - Players:  90,200 (Bullet Hell)

2018-06-29T06:34:17.664779+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Planet  34 (Captured:  0.00%) - Hard: 63 - Medium: 15 - Easy: 18 - Players:       0 (Mouse Only)

2018-06-29T06:34:17.664945+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Selected Next Zone 0 on Planet 34 (Captured:   NaN% - Difficulty: Hard)

2018-06-29T06:34:17.664950+00:00 app[salien.1]: 

2018-06-29T06:34:17.959956+00:00 app[salien.1]: [06:34:17] (sakhjack) >> Leaving planet 30, because we want to be on 34

2018-06-29T06:34:18.011220+00:00 app[salien.1]: [06:34:18] (sakhzero) >> Leaving planet 30, because we want to be on 31

2018-06-29T06:34:18.763733+00:00 app[salien.1]: [06:34:18] (sakhjack) >> Leaving planet 30, because we want to be on 34

2018-06-29T06:34:18.825442+00:00 app[salien.1]: [06:34:18] (sakhzero) >> Leaving planet 30, because we want to be on 31`
last 2 line repeat a bunch then 
`2018-06-29T06:37:29.162097+00:00 app[salien.1]: [06:37:29] (sakhjack) FetchError: For ITerritoryControlMinigameService/GetPlayerInfo/v0001

2018-06-29T06:37:29.162183+00:00 app[salien.1]: {

2018-06-29T06:37:29.162190+00:00 app[salien.1]:   "message": "invalid json response body at https://community.steam-api.com/ITerritoryControlMinigameService/GetPlayerInfo/v0001/?access_token=ec5cc7d499d4cc093400f5c84618ec55 reason: Unexpected token < in JSON at position 0",

2018-06-29T06:37:29.162191+00:00 app[salien.1]:   "type": "invalid-json"

2018-06-29T06:37:29.162193+00:00 app[salien.1]: }

2018-06-29T06:37:29.162312+00:00 app[salien.1]: [06:37:29] (sakhjack) Retrying ITerritoryControlMinigameService/GetPlayerInfo/v0001 in 3 seconds...`
and they repeat again...
